#!/bin/zsh
export vars_path="$HOME/.config/zsh/core/01_variables.sh" 
if [ ! -f "$vars_path" ]; then
  echo "[ERROR] File [$vars_path] not found !!"
  exit 3
fi

source "$vars_path"

if [ -z "$MS_GIT_REPOS" ]; then
  echo "[ERROR] Variable [MS_GIT_REPOS] is not defined !"
  exit 1
fi

if [ -z "$1" ]; then
  echo "[ERROR] No argument supplied"
  exit 2
fi

git init --bare --shared "$MS_GIT_REPOS/$1.git" && echo "[DONE]"

