#!/bin/sh


# ------------------------------------------------------ Init snap
sudo apt install snapd
sudo snap install core

# ------------------------------------------------------ Dev
# git TUI
snap install lazygit-gm
echo "alias lazygit=lazygit-gm" >> "$HOME/.config/zsh/custom/06_aliases.zsh"

# ------------------------------------------------------ TUI
# pretty top
snap install btop
# pretty ps
snap install procs
