#!/bin/sh

# ------------------------------------------------------ Shells
apt install zsh

# ------------------------------------------------------ Languages
# C/C++
apt install gcc cmake
# GO
apt install golang

# ------------------------------------------------------ Lib
apt install pkg-config libncursesw5-dev libreadline-dev

# ------------------------------------------------------ Dev
# sqlite
apt install sqlite3
# git TUI
apt install lazygit
# VIM :)
apt install neovim

# ------------------------------------------------------ TUI
# cURL
apt install curl
# pretty cat
apt install bat
# pretty top
apt install htop
# file change monitor
apt install fswatch
# fuzzy finder
apt install fzf
# JSON processor
apt install jq
# Web navigator
apt install links
# Welcome TUI
apt install neofetch
# File manager
apt install ranger
# speedtest
apt install speedtest
# symlink farm manager
apt install stow
# TCP comm
apt install telnet
# terminal multiplexer
apt install tmux
# dir tree
apt install tree
# web downloader
apt install wget
