#!/bin/sh

# ------------------------------------------------------ BAT
if [[ command -v batcat ]]; then
  sudo ln -s $(type batcat) /usr/bin/bat
fi


# ------------------------------------------------------ NodeJs
export NVM_DIR=~/.config/nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
if ! command -v nvm >/dev/null 2>&1; then
  curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi
if command -v nvm >/dev/null 2>&1; then
  # install last nodejs/npm
  nvm install --lts --latest-npm

  # install tools
  npm install -g @bitwarden/cli
fi


# ------------------------------------------------------ Rust
export PATH=$PATH:$HOME/.cargo/bin
if ! command -v cargo >/dev/null 2>&1; then
  # install rustup
  curl https://sh.rustup.rs -sSf | sh
fi
if command -v cargo >/dev/null 2>&1; then
  # pretty ls
  if ! command -v exa >/dev/null 2>&1; then
    cargo install exa
  fi
  # pretty ps
  if ! command -v procs >/dev/null 2>&1; then
    cargo install procs
  fi
  # pretty grep [rg]
  if ! command -v ripgrep >/dev/null 2>&1; then
    cargo install ripgrep
  fi
fi

# ------------------------------------------------------ Starship
sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes

# ------------------------------------------------------ Activate ZSH
chsh "$USER" -s /bin/zsh

# ------------------------------------------------------ clear motd
sudo chmod a-x /etc/update-motd.d/*
